module;
#include <type_traits>
#include <utility>
module zenith.ast;
import zenith.core.polymorphic;
#define ACCEPT_METHOD(Node) void Node::accept(Visitor& visitor) {visitor.visit(*this);} \
void Node::accept(PolymorphicVisitor& visitor, std_P3019_modified::polymorphic<ASTNode> x) {visitor.visit(std::move(x).unchecked_cast<std::remove_pointer_t<decltype(this)>>());}
namespace zenith {
	ACCEPT_METHOD(VarDeclNode)
	ACCEPT_METHOD(FunctionDeclNode)
	ACCEPT_METHOD(MemberDeclNode)
	ACCEPT_METHOD(LambdaNode)
	ACCEPT_METHOD(OperatorOverloadNode)
	ACCEPT_METHOD(ObjectDeclNode)
	ACCEPT_METHOD(UnionDeclNode)
	ACCEPT_METHOD(ActorDeclNode)
	ACCEPT_METHOD(MultiVarDeclNode)
	ACCEPT_METHOD(LiteralNode)
	ACCEPT_METHOD(VarNode)
	ACCEPT_METHOD(BinaryOpNode)
	ACCEPT_METHOD(UnaryOpNode)
	ACCEPT_METHOD(CallNode)
	ACCEPT_METHOD(MemberAccessNode)
	ACCEPT_METHOD(FreeObjectNode)
	ACCEPT_METHOD(ArrayAccessNode)
	ACCEPT_METHOD(NewExprNode)
	ACCEPT_METHOD(ExprStmtNode)
	ACCEPT_METHOD(EmptyStmtNode)
	ACCEPT_METHOD(ReturnStmtNode)
	ACCEPT_METHOD(TemplateStringNode)
	ACCEPT_METHOD(ThisNode)
	ACCEPT_METHOD(StructInitializerNode)
	ACCEPT_METHOD(LambdaExprNode)
	ACCEPT_METHOD(ProgramNode)
	ACCEPT_METHOD(ImportNode)
	ACCEPT_METHOD(AnnotationNode)
	ACCEPT_METHOD(ErrorNode)
	ACCEPT_METHOD(TemplateParameter)
	ACCEPT_METHOD(TemplateDeclNode)
	ACCEPT_METHOD(BlockNode)
	ACCEPT_METHOD(ScopeBlockNode)
	ACCEPT_METHOD(IfNode)
	ACCEPT_METHOD(WhileNode)
	ACCEPT_METHOD(DoWhileNode)
	ACCEPT_METHOD(ForNode)
	ACCEPT_METHOD(UnsafeNode)
	ACCEPT_METHOD(CompoundStmtNode)
	ACCEPT_METHOD(TypeNode)
	ACCEPT_METHOD(PrimitiveTypeNode)
	ACCEPT_METHOD(NamedTypeNode)
	ACCEPT_METHOD(ArrayTypeNode)
	ACCEPT_METHOD(TemplateTypeNode)
	ACCEPT_METHOD(FunctionTypeNode)
}
